/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_traits_Sample1 */

#ifndef _Included_com_traits_Sample1
#define _Included_com_traits_Sample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_traits_Sample1
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_traits_Sample1_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
